### ISSUE TITLE
Startup time got worse with .NET 6

### ISSUE THREAD

**Issue by tipa** [jonathanpeppers/maui-profiling#16]
First of all, thanks a lot for your continued efforts that you put into optimizing startup times & the profiling script!
Today, I started porting my (Xamarin.Android) apps to the new .NET 6 project style and used basically the default .csproj setting. The only lines I added are:
```
    <AndroidKeyStore>True</AndroidKeyStore>
    <AndroidSigningKeyStore>app.keystore</AndroidSigningKeyStore>
    <AndroidSigningKeyAlias>alias_name</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass>secret_pw</AndroidSigningKeyPass>
    <AndroidSigningStorePass>secret_pw</AndroidSigningStorePass>
    <AndroidLinkResources>True</AndroidLinkResources>
    <AndroidLinkTool Condition="'$(Configuration)' == 'Release'">r8</AndroidLinkTool>
```

In my old .csproj, I used these settings:
```
    <AndroidManagedSymbols>true</AndroidManagedSymbols>
    <AndroidLinkMode>Full</AndroidLinkMode>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidSupportedAbis>armeabi-v7a;x86;x86_64;arm64-v8a</AndroidSupportedAbis>
    <AotAssemblies>false</AotAssemblies>
    <EnableLLVM>false</EnableLLVM>
    <AndroidCreatePackagePerAbi>false</AndroidCreatePackagePerAbi>
    <AndroidPackageFormat>aab</AndroidPackageFormat>
    <AndroidLinkTool>r8</AndroidLinkTool>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <BundleAssemblies>false</BundleAssemblies>
    <AndroidKeyStore>true</AndroidKeyStore>
    <AndroidSigningKeyStore>app.keystore</AndroidSigningKeyStore>
    <AndroidSigningKeyAlias>alias_name</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass>secret_pw</AndroidSigningKeyPass>
    <AndroidSigningStorePass>secret_pw</AndroidSigningStorePass>
    <LangVersion>10.0</LangVersion>
    <AndroidHttpClientHandlerType>Xamarin.Android.Net.AndroidClientHandler</AndroidHttpClientHandlerType>
    <AndroidTlsProvider>btls</AndroidTlsProvider>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
    <AndroidDexTool>d8</AndroidDexTool>
    <AndroidEnableMultiDex>false</AndroidEnableMultiDex>
```

With the .NET 6 app, the app size did slightly reduce (but not always, sometimes it was even bigger, but that's a separate issue).
However, the startup times did increase (by ~40%). I tested this with two separate apps I ported.
Previously ("Xamarin.Android"), the startup time was ~800-900ms, now it is ~1150-1400ms, which surprised me because your numbers measured for a blank app show that the startup time should be smaller than before. And I would have expected at least same startup performance as I tried to use the same built options as before (partial AOT/startup tracing, R8, no LLVM, full linking, aapt2, ...)

All tests were performed with the apps built in Release mode on a Samsung A52.

Am I doing something wrong?
Please let me know if this is not the right repo to post this issue, I can also file a report on the xamarin-android repo

**Comment by jonathanpeppers** [comment]
You might be able to use this setting in .NET 6 if it was working in Xamarin:
```xml
 <AndroidLinkMode>Full</AndroidLinkMode>
 ```

I'm a little confused by these two settings, was this the `Debug` configuration?
```
<AotAssemblies>false</AotAssemblies>
<AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
```
These are the default in .NET 6 for `Release` builds.

Does your app use Xamarin.Forms/MAUI at all? If not, the issue might be that our `.aotprofile` isn't bringing in what your app needs.

Can you get `.speedscope` file of your app with `dotnet trace` ([instructions here](https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/tracing.md)) and share it here? Thanks!

**Comment by tipa** [comment]
Thanks for your quick response!

> You might be able to use this setting in .NET 6 if it was working in Xamarin:
> 
> ```
>  <AndroidLinkMode>Full</AndroidLinkMode>
> ```

Oh, I thought that setting was deprecated and not used in .NET any more in favor of `PublishTrimmed` etc., that's why I didn't use it. So looks like I still have to specify it if I want to link/trim **all** assemblies, right?

> I'm a little confused by these two settings, was this the `Debug` configuration?
> 
> ```
> <AotAssemblies>false</AotAssemblies>
> <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
> ```
> 

No it was Release config, but it was the wrong app. In my other apps, I have `AotAssemblies` set to false and `AndroidEnableProfiledAot` set to true. So I made another test with another app of mine that previously had startup-tracing enabled (not full AOT). And in my .NET6 app I now use these settings:

```
    <AndroidLinkResources>True</AndroidLinkResources>
    <AndroidLinkTool Condition="'$(Configuration)' == 'Release'">r8</AndroidLinkTool>
    <AndroidLinkMode Condition="'$(Configuration)' == 'Release'">Full</AndroidLinkMode>
```


> Does your app use Xamarin.Forms/MAUI at all?

No, I am using "pure" .NET 6 for Android


> Can you get `.speedscope` file of your app with `dotnet trace` ([instructions here](https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/tracing.md)) and share it here? Thanks!

I did create the file but would it be possible to share it privately?

**Comment by jonathanpeppers** [comment]
> Oh, I thought that setting was deprecated and not used in .NET any more in favor of PublishTrimmed etc., that's why I didn't use it. So looks like I still have to specify it if I want to link/trim all assemblies, right?

Yes there isn't a new MSBuild property that is the equivalent of `$(AndroidLinkMode)`, so we kept it.

> So I made another test with another app of mine that previously had startup-tracing enabled (not full AOT)

One thing that might be different is the AOT profile isn't matching as many methods in your app in .NET 6. Some ideas there:

* If you do `adb shell setprop debug.mono.log default,mono_log_level=debug,mono_log_mask=aot`, you can see `AOT NOT FOUND` log messages.
* You can get the [`methods.txt`](https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/profiling.md#profiling-the-jit-compiler) file for your app, and see what the top JIT'd methods are
* Record a custom AOT profile for your app with [`Mono.AotProfiler.Android`](https://github.com/jonathanpeppers/Mono.Profiler.Android#usage-of-the-aot-profiler) NuGet package

> I did create the file but would it be possible to share it privately?

If you like you can email me at the address on my GitHub profile. The file would mostly have method names in it, but maybe you wouldn't want that to be public. Thanks!

**Comment by tipa** [comment]
I created a custom AOT profile as you suggested and the results got even worse (startup times increased by another ~130ms) - I've seen a similar behavior before in Xamarin.Android apps which is why I stuck with the default profile.

I also tried enabling full AOT by adding these 3 lines to the .csproj, but the startup time did not improve and was still worse than my old Xamarin.Android app:
```
  <RunAOTCompilation>true</RunAOTCompilation>
  <EnableLLVM>true</EnableLLVM>
  <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
```

I will send you the .speedcope file via mail, maybe it contains any clues.
Thanks again for your help.

**Comment by tipa** [comment]
After communication via mail I did more tests:

Xamarin.Android: 760 Ms startup, 35.89 MB installed size
.net6, build via IDE: 1040 Ms, 24.12 MB
.net6, build via command line: 930 Ms, 30.23 MB
.net6, custom aot profile, IDE: 1074 Ms, 24.23 MB
.net6, custom aot profile, command line: 650 Ms, 31.40 MB

So some things are interesting here:
- there really seems to be a problem when using the build/deploy button in the IDE. Perhaps it doesn't take some csproj properties into consideration which causes less startup optimizations and ignores the custom aot profile
- .net6 build without custom aot profile results in longer startup time (but much smaller app size) compared to Xamarin.Android where I used similar build settings. So somehow the default AOT profile now leads to worse results?
- **custom aot profile results in smaller app size AND faster startup compared to Xamarin.Android -  nice!** However, only when built using command line.

**Comment by jonathanpeppers** [comment]
The IDE issue is caused by interaction between how the IDE deploys and the `<MonoAOTCompiler/>` task...

https://github.com/xamarin/xamarin-android/blob/294208fea55d80e36e9e8f28e9bae351bd063965/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Aot.targets#L97

The IDE does a `Build`, then `Install` to deploy. During `Install` the `_AndroidAot` target is skipped, `@(_AotCompiledAssemblies)` is empty, and the `libaot-*.so` files don't make it to the app.

For this to work right, we can't use the output items of `<MonoAOTCompiler/>` task. I'll look into a fix for a future service release.

**Comment by tipa** [comment]
Thank you!

What happens in the Archiving process when I build an archive for the app store? Does it include the AOT'd assemblies also when clicking everything in the IDE or should I first build die app using the command line?

Is there an open issue for this problem that I can track? I can also open one if needed

**Comment by jonathanpeppers** [comment]
I am partial to using something like Github actions/Azure DevOps to build apps anyway. I *think* the archiving UI might work, because it runs a target by itself. You can check if these files are missing (this app is named `ggggg`):

![image](https://user-images.githubusercontent.com/840039/174308625-40ef462e-7ddf-485b-bcbd-8317f94b1c85.png)
