### ISSUE TITLE
Way to automate ios startup time measurement

### ISSUE THREAD

**Issue by Pastajello** [jonathanpeppers/maui-profiling#29]
Hello!

I really like to work you do. Its working nicely for my application, but here I sit and wonder, is it possible to have a similar script for ios? 
If so, Im not saying to have you write it up, but can you maybe give a starting point for it?

**Comment by jonathanpeppers** [comment]
I think they have some examples here:
* https://github.com/dotnet/performance/pull/3352

Using a tool called `xharness` (was short for Xamarin) to launch iOS apps:
* https://github.com/dotnet/xharness
